### ISSUE TITLE
What exact prompt is used on the math dataset (Table 8)?

### ISSUE THREAD

**Issue by soumyapal91** [chuanyang-Zheng/Progressive-Hint#10]
Would you please upload the exact 'Complex CoT' prompt that you used on the math dataset (Table 8)? Thanks!

**Comment by chuanyang-Zheng** [comment]
please check here. https://github.com/chuanyang-Zheng/Progressive-Hint/tree/main/prompt/complex

**Comment by soumyapal91** [comment]
Thank you very much!
