### ISSUE TITLE
Will the prompt for MATH dataset be released?

### ISSUE THREAD

**Issue by XinXU-USTC** [chuanyang-Zheng/Progressive-Hint#7]
I am interested in the prompts for MATH dataset. Will that part be released in the future? Thank you!

**Comment by chuanyang-Zheng** [comment]
We are sorry that we reply late. The MATH dataset prompt is here.
https://github.com/chuanyang-Zheng/Progressive-Hint/tree/main/prompt/complex

If we do not reply on time, please remind us via email cyzheng21@cse.cuhk.edu.hk or cyzhengme@gmail.com.

Again, thank you very much for your attention. And we are really sorry for the late reply.

**Comment by XinXU-USTC** [comment]
Thank you for your help!
